name: Build

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - "3.2"
          - "3.1"
          - "3.0"
          - "2.7"
          - "jruby"
          - "truffleruby"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run StandardRB
      run: bundle exec standardrb
    - name: Run RSpec
      run: bundle exec rspec
